### ISSUE TITLE
Is it possible to make any mappings to network drive(s)?

### ISSUE THREAD

**Issue by niekniek89** [hassio-addons/addon-sonarr#7]
First of all, this is not an issue but a question (I can't find it on discord).
Is it possible to use this addon to create a network mapping with, for example, a NAS?

**Comment by frenck** [comment]
Sonarr allows making mappings (that is unrelated to the mappings, as Sonarr is only aware of the local file system, including its mounts, regardless of source).

Home Assistant allows you to add network storage in its settings menu, which would be available to Sonarr (and thus its mapping).

../Frenck

**Comment by Caligo82** [comment]
I'm running homeassistant supervised within debian bookworm. In the settings menu it tells me:

'The operating system does not support network storage
Network storage is not supported on this host'

Should I mount these network drives in debian? However since Sonarr is running in a docker container it would have to be mounted there as well... is there any way to do this?

**Comment by frenck** [comment]
> I'm running homeassistant supervised within debian bookworm. In the settings menu it tells me:

So, you manage your OS, you can mount / do it any way you like. You picked that installation method, because you have the knowledge and want the flexibility to make your own calls on that level.

../Frenck

**Comment by Caligo82** [comment]
It's not like I expected a "one press do it all button" on request. But maybe a hint on how to do this without losing a healthy system.

One might argue that during the time it took you to write those lines you could have given a hint on how to proceed.

A more general question regarding this issue: do we have to expect to drop plugin support for homeassistant if we are using a (officially supported) debian installation?
